### ISSUE TITLE
Update Serilog.Sinks.ExcelDnaLogDisplay build process to use Cake v2.3.0

### ISSUE THREAD

**Issue by augustoproiete** [serilog-contrib/serilog-sinks-exceldnalogdisplay#43]
[Cake 2.3.0](https://cakebuild.net/blog/2022/10/cake-v2.3.0-released) has been released  🎉

**Comment by gauravagrwal** [comment]
Hi @augustoproiete, will it be okay if I work on this one.

**Comment by augustoproiete** [comment]
@gauravagrwal Sure. Go for it!
